import Head from 'next/head'
const MainLayout = ({children,title}) => {
    return (
        <>
          <Head>
            <title>{title}</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main>
            {children}
          </main>
        </>
      )
}

MainLayout.defaultProps ={
    title:"ArchAI"
}
 
export default MainLayout;